<?php

namespace App\Http\Controllers\Auth;

use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Laravel\Socialite\Facades\Socialite;

class GoogleController extends Controller
{
    public function redirectToGoogle(): RedirectResponse
    {
        return Socialite::driver('google')->redirect();
    }

    public function handleGoogleCallback(): RedirectResponse
    {
        $user = Socialite::driver('google')->user();

        $existingUser = User::where('google_id', $user->id)->first();

        if ($existingUser) {
            // Log in the existing user.
            Auth::login($existingUser, true);
        } else {


            // Create a new user.
            $newUser = new User();
            $newUser->name = $user->name;
            $newUser->slug = Str::slug($user->name);
            $newUser->email = $user->email;
            $newUser->google_id = $user->id;
            $newUser->password = bcrypt(request(Str::random())); // Set some random password
            $newUser->image = getSocialAvatar($user->getAvatar(), '/uploads/users/', $user);
            $newUser->wallet = '0.00';
            $newUser->earnings = '0.00';

            if ($newUser->save()) {

                Auth::login($newUser);

            }

        }

         // Redirect to url as requested by user, if empty use /dashboard page as generated by Jetstream
        return redirect()->route('home');
    }
}
